<a href="https://colab.research.google.com/github/bhavanakodali5/IIIT-AI-ML-COURSE/blob/main/Basics_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basics of Linear Algebra

Import the NumPy library for Linear Algebra functions and Matplotlib for some plotting functions.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Transpose of Matrix

Matrix transpose is performed with the transpose method on a nested list or a Python array, or a higher-dimensional Numpy array.

In [2]:
 # Transpose of a Matrix (as nested list)
 a = [[1,2,3,4],[2,3,4,5]]
 b = np.transpose(a)
 print('a\n',a)
 print('b\n',b)

a
 [[1, 2, 3, 4], [2, 3, 4, 5]]
b
 [[1 2]
 [2 3]
 [3 4]
 [4 5]]


If the matrix is a NumPy array, it can be treated as an object and method T can be applied over it as follows.

In [3]:
  # Transpose of a Matrix (as NumPy array)
print ("Matrix and its Transpose")
a = np.array([[1,2,3,4],[2,3,4,5]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[1 2 3 4]
 [2 3 4 5]]
b
 [[1 2]
 [2 3]
 [3 4]
 [4 5]]


The dot method of NumPy performs dot-matrix product (scalar product) for 1D or higher dimensional arrays. If the inputs are scalars (numbers), it performs multiplication.

In [4]:
 # scalars
 a = 5
 b = 3
 z = np.dot(a,b)
 print(z)

15


In [5]:
 z = a * b
 print(z)

15


In the case of one- or higher-dimensional arrays, the inputs can be either NumPy arrays, Python arrays, Python lists or Python’s nested lists.

In [6]:
 # 1D arrays or vectors
 a = np.array([1,2,3])  # or a = [1,2,3]
 b = np.array([2,3,4])  # or b = [2,3,4]
 z = np.dot(a,b)
 print(z)


20


In [7]:
 # 2D arrays or matrices
 a = [[1,2,3],[2,0,3],[7,-5,1]]
 b = [[3,-1,5],[-2,-6,4], [0,4,4]]
 z = np.dot(a,b)
 print(z)


[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


We can obtained the same result using `np.matmul()`.

In [8]:
z = np.matmul(a,b)
print(z)

[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


### Numpy Arrays
A NumPy array is a Numpy object upon which the dot method can be performed as below. However, this method accepts only NumPy arrays to operate on.


In [9]:
 # convert lists into NumPy arrays
 newa = np.array(a)
 newb = np.array(b)
 z = newa.dot(newb)
 print(z)

[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


### Inner Product

The inner product is the scalar multiplication of one vector (or matrix) and the transpose of another vector (or matrix). If both arrays are 1D arrays, their dimensions should be identical. If either or both arrays are higher-dimensional, then the last dimensions of both arrays should be identical.

In [11]:
 a = np.array([[1,2,3], [4,-1,0]])
 b = np.array([6,3,2])
 z = np.inner(a,b)
 print(z)

[18 21]


In [12]:

# The same results can be obtained using the dot method as follows.

a.dot(b.T)

array([18, 21])

### Outer Product

Outer product is the dot product of a column vector of size Mx1 and a row vector of size 1xN. The resulting array is a matrix of size MxN.


In [13]:
 a = np.array([1,2,3,4,5])
 b = np.array([6,3,2])
 z = np.outer(a,b)
 print(z)

[[ 6  3  2]
 [12  6  4]
 [18  9  6]
 [24 12  8]
 [30 15 10]]


The last dimension of the second array and the second-to-last dimension of the first array should be identical to perform matrix multiplication. Further, the symbol @ is also used to perform matrix multiplication.

In [14]:
 # Here, 'a' matrix is 3D, which means there are 3 matrices each of 2x5 size
 # Similarly, for 'b' matrix
 # So we perform 3 matrix multiplication operations each with 2x5 and 5x3 matrices from a and b
 a = np.random.random([3,2,5])
 b = np.random.random([3,5,3])
 z = a @ b
 print(z.shape)

(3, 2, 3)


### Matrix Determinant

Matrix determinant can be calculated using the method det available in the linalg module.

In [15]:
 # generate a random integer matrix of size 3 by 3
 a = np.random.randint(1,10,[3,3])
 det = np.linalg.det(a)
 print(int(det))

461


### Matrix Inverse

Inverse of a square matrix can be derived using the inv method of the linalg module.


In [16]:
 a = np.random.randint(1,10,[3,3])
 inv = np.linalg.inv(a)
 print(a)
 print()
 print(inv)


[[2 5 9]
 [4 7 9]
 [8 5 5]]

[[ 0.11904762 -0.23809524  0.21428571]
 [-0.61904762  0.73809524 -0.21428571]
 [ 0.42857143 -0.35714286  0.07142857]]


### Traces of a Matrix

Traces of a square matrix is the summation of its diagonal elements.

In [ ]:
a = np.eye(5)
print(a)
z = np.trace(a)
print('\nTrace of matrix is: ',z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of matrix is:  5.0
